### ISSUE TITLE
Confused about the step in Tutorial "BLOB_STORAGE_CONNECTION_STRING" and "AzureWebJobsStorage" setting.

### ISSUE THREAD

**Issue by CapitaineNemo** [MicrosoftDocs/azure-dev-docs#1009]
https://learn.microsoft.com/en-us/azure/developer/python/tutorial-deploy-azure-cloud-python-etl-03-process-data
Confused about the step in Tutorial "BLOB_STORAGE_CONNECTION_STRING" and "AzureWebJobsStorage" setting.
@diberry  I still cannot get it. If the two values point to different accounts. And why is the value same? In my opinion. Nether running locally nor  deployed, because they controll two different storage accounts. 
AzureWebJobsStorage is msdocspythoncloud1 connection string. And in the guide I cannot find which link it should link BLOB_STORAGE_CONNECTION_STRING. But I suppose that it should be msdocspythoncloudetladls. 

<img width="456" alt="image" src="https://user-images.githubusercontent.com/25415402/210753615-8defbea7-d732-41ad-bc1d-9fa9f88b5ea6.png">

_Originally posted by @CapitaineNemo in https://github.com/MicrosoftDocs/azure-dev-docs/issues/1006#issuecomment-1372012082_

**Comment by diberry** [comment]
@CapitaineNemo This is a great point and the content should be updated. Would you be interested in jumping on a call to discuss this article series? You've invested time and it would be great to understand any other insights you have to making this series more understandable. 

For your specific question: 

When you are running locally on your own dev box, you can use a single blob storage account for all the accounts needed. You can even use the [Azure Storage emulator](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-emulator) so all the work is local to your computer while in development.

When you move to cloud deployment, you will have at least 2 storage accounts but more than likely, if you follow this article, 3. 

* AzureWebJobsStorage: Azure Functions needs its own storage account so it can manage the various work done by any triggers. You wouldn't want this to be the same account as your data accounts because you wouldn't want to clobber what storage items your Azure Function needs. When you create your Function resource, this storage account is created for you.
* BLOB_STORAGE_RESOURCE_NAME: This is the account that receives the initial news items from Bing Search. It doesn't have to have hierarchical folders enabled. 
* DATALAKE_GEN_2_RESOURCE_NAME: This is the data lake account that receives the final, transformed news items. It must have hierarchical folders enabled. 


Can  BLOB_STORAGE_RESOURCE_NAME and DATALAKE_GEN_2_RESOURCE_NAME be the same resource? Sure, if hierarchical folders is enabled? 

Can all 3 use the same storage account? Maybe. I'm not sure what the requirements are for storage for Azure Functions. Since I can't guarantee over time that the Azure Functions requirements won't drift from hierarchical folders (datalake capability), I choose to personally let functions create its own storage account and never touch that storage directly. 

If this information is helpful, let me know and I'll add it to the doc. Would it be more helpful upfront on the first page or as each storage resource is created and used? 

#in-progress

**Comment by CapitaineNemo** [comment]
> @CapitaineNemo This is a great point and the content should be updated. Would you be interested in jumping on a call to discuss this article series? You've invested time and it would be great to understand any other insights you have to making this series more understandable.
> 
> For your specific question:
> 
> When you are running locally on your own dev box, you can use a single blob storage account for all the accounts needed. You can even use the [Azure Storage emulator](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-emulator) so all the work is local to your computer while in development.
> 
> When you move to cloud deployment, you will have at least 2 storage accounts but more than likely, if you follow this article, 3.
> 
> * AzureWebJobsStorage: Azure Functions needs its own storage account so it can manage the various work done by any triggers. You wouldn't want this to be the same account as your data accounts because you wouldn't want to clobber what storage items your Azure Function needs. When you create your Function resource, this storage account is created for you.
> * BLOB_STORAGE_RESOURCE_NAME: This is the account that receives the initial news items from Bing Search. It doesn't have to have hierarchical folders enabled.
> * DATALAKE_GEN_2_RESOURCE_NAME: This is the data lake account that receives the final, transformed news items. It must have hierarchical folders enabled.
> 
> Can BLOB_STORAGE_RESOURCE_NAME and DATALAKE_GEN_2_RESOURCE_NAME be the same resource? Sure, if hierarchical folders is enabled?
> 
> Can all 3 use the same storage account? Maybe. I'm not sure what the requirements are for storage for Azure Functions. Since I can't guarantee over time that the Azure Functions requirements won't drift from hierarchical folders (datalake capability), I choose to personally let functions create its own storage account and never touch that storage directly.
> 
> If this information is helpful, let me know and I'll add it to the doc. Would it be more helpful upfront on the first page or as each storage resource is created and used?
> 
> #in-progress

Hi, thanks for your reply. Ok, we can have a call to discuss it. You can find my Teams ID djinyu@werfen.com
