### ISSUE TITLE
Code as given on page fails to execute

### ISSUE THREAD

**Issue by spellinn** [MicrosoftDocs/azure-dev-docs#1061]
The error is:

```
 Error: Reference to undeclared resource
│
│   on output.tf line 28, in output "AVD_user_groupname":
│   28:   value       = azuread_group.aad_group.display_name
│
│ A managed resource "azuread_group" "aad_group" has not been declared in the root module. 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a0a97cf-1514-889c-edbc-9c10bd566231
* Version Independent ID: 3a0a97cf-1514-889c-edbc-9c10bd566231
* Content: [Configure Azure Virtual Desktop using Terraform - Azure](https://learn.microsoft.com/en-us/azure/developer/terraform/configure-azure-virtual-desktop)
* Content Source: [articles/terraform/configure-azure-virtual-desktop.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/configure-azure-virtual-desktop.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by alexgabriel-ca** [comment]
I've had this exact same issue when using the code from https://learn.microsoft.com/en-us/azure/developer/terraform/create-avd-session-host with terraform 1.5.6

The output I get is shown below
`╷
│ Error: Reference to undeclared resource
│
│   on main.tf line 2, in locals:
│    2:   registration_token = azurerm_virtual_desktop_host_pool_registration_info.registrationinfo.token
│
│ A managed resource "azurerm_virtual_desktop_host_pool_registration_info"
│ "registrationinfo" has not been declared in the root module.
╵
╷
│ Error: Reference to undeclared resource
│
│   on main.tf line 26, in resource "azurerm_network_interface" "avd_vm_nic":
│   26:     subnet_id                     = azurerm_subnet.subnet.id
│
│ A managed resource "azurerm_subnet" "subnet" has not been declared in the
│ root module.
╵
╷
│ Error: Reference to undeclared resource
│
│   on output.tf line 13, in output "dnsservers":
│   13:   value       = azurerm_virtual_network.vnet.dns_servers
│
│ A managed resource "azurerm_virtual_network" "vnet" has not been declared
│ in the root module.
╵
╷
│ Error: Reference to undeclared resource
│
│   on output.tf line 18, in output "vnetrange":
│   18:   value       = azurerm_virtual_network.vnet.address_space
│
│ A managed resource "azurerm_virtual_network" "vnet" has not been declared
│ in the root module.
`

The code used was copied and pasted direct from the MS site noted above.

**Comment by alexleach** [comment]
Over a year later, and still a bug in the code. Any suggestions?

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close

**Comment by alexleach** [comment]
Hi @TomArcherMsft ,

Thanks for the candid and prompt response.

Well, the coding error listed above in this Issue is fairly specific and to-the-point, and is still present in the example code, so I don't think this issue should be closed. That is, the `azuread_group.aad_group` resource is not defined in the code, so the example code does not work. As a relative newb to Terraform, this took quite a bit of investigation for me to sort out. Personally, I defined a `data` resource and referred to an existing group in Entra ID.

This Issue pertains to the first page in the series. It doesn't get much better from there, if I'm being totally honest. I'd rather not create separate issues for each page and point, as I personally think the whole series should be updated and refactored.

As such, I'd rather list out some issues I've had with the example code as general feedback for improvement.

I only went through the first four articles in the series:

- [Configure Azure Virtual Desktop with Terraform](https://learn.microsoft.com/en-us/azure/developer/terraform/configure-azure-virtual-desktop)
- [Create a Host](https://learn.microsoft.com/en-us/azure/developer/terraform/create-avd-session-host)
- [Configure RBAC Permissions](https://learn.microsoft.com/en-us/azure/developer/terraform/configure-avd-rbac)
- [Configure Network settings](https://learn.microsoft.com/en-us/azure/developer/terraform/configure-avd-network-settings)
- etc..

I spent the best part of a week trying to get it working, and sadly still haven't got it fully functioning...

Anyway, here are some suggestions which I think will improve this How-To series:

### Introduction

An Introduction or Overview page should be included specifying the design of the target infrastructure. Sadly, for met at least, the target infrastructure is an AD-joined Session Host. I instead had hoped to create Entra-joined session hosts, as described in the separate article [Tutorial: Deploy a sample Azure Virtual Desktop infrastructure with a Windows 11 desktop](https://learn.microsoft.com/en-us/azure/virtual-desktop/tutorial-try-deploy-windows-11-desktop?tabs=windows-client).

### Repetitive and unclear information at the top of each page

Each page repeats the same introductory information and Configure Your Environment section, e.g. [on the first Page](https://learn.microsoft.com/en-us/azure/developer/terraform/configure-azure-virtual-desktop#1-configure-your-environment). Instead, I think each first section should just refer back to the previous page / pages.

### How to cross-link the code?

On the second page [Create a Host](https://learn.microsoft.com/en-us/azure/developer/terraform/create-avd-session-host):

> This article assumes you've already deployed the [Azure Virtual Desktop Infrastructure](https://learn.microsoft.com/en-us/azure/developer/terraform/configure-azure-virtual-desktop). _(It's referring back to the first article in the series)_

Okay, how do I refer to resources from the first article then? The [second section](https://learn.microsoft.com/en-us/azure/developer/terraform/create-avd-session-host#2-implement-the-terraform-code) gives an entirely new `main.tf`, `variables.tf` and `output.tf` file. How then, do I refer to the resources and variables from the first article? I guess I should append to the existing files, but that is obviously unclear.

### Outdated Module Reference?

On the [Create a Host page](https://learn.microsoft.com/en-us/azure/developer/terraform/create-avd-session-host#2-implement-the-terraform-code), when configuring the `AddSessionHost` Desired State Configuration, it refers to an old Configuration module:

```json
    {
      "modulesUrl": "https://wvdportalstorageblob.blob.core.windows.net/galleryartifacts/Configuration_09-08-2022.zip",
      "configurationFunction": "Configuration.ps1\\AddSessionHost",
      "properties": {
        "HostPoolName":"${azurerm_virtual_desktop_host_pool.hostpool.name}"
      }
    }
```

After creating a functioning AVD using the Tutorial I referred to above, I exported the JSON file and compared the link. The `modulesUrl` there is `https://wvdportalstorageblob.blob.core.windows.net/galleryartifacts/Configuration_1.0.02608.268.zip`.

How do I even figure out what the URL and version should be? Is there any way of finding this out, other than creating a Session Host in the Azure Portal and inspecting the JSON?

### Reference to infrastructure not built yet

Still on the [Create a Host page](https://learn.microsoft.com/en-us/azure/developer/terraform/create-avd-session-host#2-implement-the-terraform-code)

> **Key Points:**
> References resources that were created when the infrastructure was built - such as azurerm_subnet.subnet.id and azurerm_virtual_desktop_host_pool.hostpool.name. If you changed the name of these resources from that section, you also need to update the references here.

When was this infrastructure built? The [Configure Network Settings page](https://learn.microsoft.com/en-us/azure/developer/terraform/configure-avd-network-settings) is two pages later. This code refers to a resource in the same module, but that resource doesn't exist in the `main.tf` file's code listed on that page. Chicken and egg problem here...

### Joining to Entra ID

I don't have an ADDS environment or DC available, so I want to join the Session Host to Entra ID. How do I do that?

I think this How-To guide should be equivalent to the [Tutorial](https://learn.microsoft.com/en-us/azure/virtual-desktop/tutorial-try-deploy-windows-11-desktop?tabs=windows-client) I linked to earlier, which I think is more relevant in today's push for Cloud-based environments.

### Alternative examples and documentation

There's a terraform module at [decensas/terraform-azurerm-azure-virtual-desktop](https://github.com/decensas/terraform-azurerm-azure-virtual-desktop). This does most of what I want, but is also fairly out of date and doesn't do everything that happens in the Tutorial code.

### Summary

Please update this How-To guide. I think it needs a substantial revamp! Currently, I have a working environment set up using the Azure Portal, but I was really hoping to get it working reproducibly in Terraform!

Oh, and it cost me quite a lot of money in non-working infrastructure attempting to get this working, I've spent £26 on non-working resources in the last week alone, and that's trying to set up just one, Personal AVD!
