### ISSUE TITLE
How to use those FileShare properties?

### ISSUE THREAD

**Issue by n-semikin** [MicrosoftDocs/azure-dev-docs#1137]
Missing details on how to use those properties. Link to FileShare sample would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 30f34d85-c1a8-8350-a8f2-3dfa80cf7380
* Version Independent ID: 30f34d85-c1a8-8350-a8f2-3dfa80cf7380
* Content: [Azure Storage File Share configuration properties](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configuration-properties-azure-storage-file-share)
* Content Source: [articles/java/spring-framework/configuration-properties-azure-storage-file-share.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configuration-properties-azure-storage-file-share.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **rujche**

**Comment by Netyyyy** [comment]
Hi @n-semikin , Could you tell me which properties you don't know how to use so that we can better help? Because not all the properties are used in [sample](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/storage/spring-cloud-azure-starter-storage-file-share/storage-file-sample).

**Comment by KarlErickson** [comment]
No reply - closing
