### ISSUE TITLE
Please add instructions on how to add os.environ['ENVIRONMENT']='Development'

### ISSUE THREAD

**Issue by Badrul-Goomblepop** [MicrosoftDocs/azure-dev-docs#1152]
Please add instructions to let Window users know that they have to run the following command to add the ENVIRONEMENT variable.

$Env:ENVIRONMENT="development"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc0b9fe1-02a3-f31f-49d9-0935c7468f6c
* Version Independent ID: cc0b9fe1-02a3-f31f-49d9-0935c7468f6c
* Content: [Authenticate Python apps to Azure services during local development using service principals](https://learn.microsoft.com/en-us/azure/developer/python/sdk/authentication-local-development-service-principal?source=recommendations&tabs=azure-portal)
* Content Source: [articles/python/sdk/authentication-local-development-service-principal.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/python/sdk/authentication-local-development-service-principal.md)
* Service: **azure-python**
* GitHub Login: @bobtabor-msft
* Microsoft Alias: **rotabor**

**Comment by JimacoMS4** [comment]
Hi @Badrul-Goomblepop,

First, my apologies for the long delay in responding to your feedback. We had an internal mix-up with a few issues. Second, thanks for taking the time to provide feedback. 

For the present, we've decided not to provide instructions on how to set the environment variable because the focus of the code snippet (and section) is really just how to set and load the environment variables necessary to authenticate with a service principal from the .env file. It's not really meant to be a full-functioned tutorial -- and, if we provide instructions for PowerShell, then we need to do the same for Windows cmd shell, bash, etc. We'll continue to monitor the topic, though, and, if we get more feedback along these lines, we'll revisit our decision. 

Thanks again, for your feedback -- even though we didn't act on it this time, we do appreciate it!

-Jimaco
