### ISSUE TITLE
Needed more information

### ISSUE THREAD

**Issue by lydiacrimedev** [MicrosoftDocs/azure-dev-docs#1264]
There was very little information about the service. I would have liked if this documentation added a bit more details.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d58c633a-e315-cc57-0783-ea5e7f4868d5
* Version Independent ID: d58c633a-e315-cc57-0783-ea5e7f4868d5
* Content: [Azure for developers overview](https://learn.microsoft.com/en-us/azure/developer/intro/azure-developer-overview)
* Content Source: [articles/intro/azure-developer-overview.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/intro/azure-developer-overview.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thank you for reaching out with your feedback about this article. We have recently reviewed it internally and came to the same conclusion as you: although it's intended by design to be a very high-level entry point to the Azure developer story, it doesn't perform that job very well at this point and it leaves the reader hanging rather abruptly. We have a work item on our backlog to revamp this article some time in the next ~6 months.

**Comment by lydiacrimedev** [comment]
Thank you for taking the time to review my feedback and I look forward to the revamp!
