### ISSUE TITLE
No available subscription found in current account

### ISSUE THREAD

**Issue by briannoble113** [MicrosoftDocs/azure-dev-docs#127]
Hi, 

I've followed the instructions above but at the point of deploying to Azure I get the following error: 

[ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.9.0:deploy (default-cli) on project spring-boot: Encoutering error when deploying to azure: 'No available subscription found in current account.'

I have a Free Trial subscription.  I can see when I run "az login" using the CLI I have a listed subscription: 

[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "e5800a50-527b-40c6-950d-3243f52fxxxx",
    "id": "f80b6596-dddb-4b54-8d21-671270baxxxx",
    "isDefault": true,
    "managedByTenants": [],
    "name": "Free Trial",
    "state": "Enabled",
    "tenantId": "e5800a50-527b-40c6-950d-3243f52fxxxx",
    "user": {
      "name": "caxxxxxxxxxx@gmail.com",
      "type": "user"
    }
  }
]

Please help.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d6851cb-0c9f-23ef-f231-ff97f44eb721
* Version Independent ID: 1fcdbb4a-ee88-9dcd-3ec9-e2064d832ceb
* Content: [Deploy a Spring Boot JAR file Web App to Azure App Service on Linux](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/deploy-spring-boot-java-app-with-maven-plugin#feedback)
* Content Source: [articles/java/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md)
* Service: **app-service**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by Scopeix** [comment]
+1,  Facing the same issue. Any idea why this is happening.

**Comment by mortezaadi** [comment]
Same issue here!

**Comment by Rachidba** [comment]
Hello,
I had the same issue and I solved it by adding "<authType>azure cli</authType>" to the azure-web-maven-plugin's configuration.
```  
<plugin>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>azure-webapp-maven-plugin</artifactId>
        <version>1.8.0</version>
        <configuration>
            <!-- Specify v2 schema -->
            <schemaVersion>v2</schemaVersion>
            <!-- App information -->
            <authType>azure cli</authType>
            <resourceGroup>RESOURCEGROUP_NAME</resourceGroup>
            <appName>WEBAPP_NAME</appName>
            …
```

**Comment by chankwpj** [comment]
same. @Rachidba 's suggestion actually works

**Comment by briannoble113** [comment]
Thanks @Rachidba that worked for me too - fantastic! +1

**Comment by KarlErickson** [comment]
We've been able to confirm this - our subject-matter expert says "This issue happens when users tried to use maven plugin before installing azure cli, thus left auth files created by Maven plugin but then try to auth with az cli later. Yes adding the auth type (azure_cli) is the right way to solve this."

**Comment by vnextcoder** [comment]
This Issue also happens if you are having AZ CLI installed within WSL 2 and running MVNW from WSL2 only.

For troubleshooting this on WSL , I tried all steps necessary to clear the Subscriptions, Set Default Subscription from Command Line and also set <subscriptionId></subscriptionId> in the pom.xml as well. 

thing is the Azure.Subscriptions.list() just returns nothing. it could be a bug within the Azure Management JAR itself, but I am not sure as of now. 

Moreover, I have also tried using Maven Azure Plugin 1.7, 1.9.1 and 1.10.0 as well. All failed on  WSL2

Once I switched to the Windows 10 native, it worked fine.

**Comment by CoryFoy** [comment]
Oh, thank you so much for this @Rachidba. I've been battling this issue for a couple of days, including seeing 401 errors even though everything seemed fine. I had indeed run the maven plugins before I had the AZ CLI installed - in my case, I went ahead and blew out `~/.azure` and then redid the `az login` (and, because I have multiple subscriptions, setting the right one with `az account`) and everything is working great.
