### ISSUE TITLE
the puppet agentusing terraform azure

### ISSUE THREAD

**Issue by THG-onkar** [MicrosoftDocs/azure-dev-docs#148]
hello
I want to deploy puppet client with terraform, was search hashicrop document for how to create azure VM with puppet configuration using terraform but didn't get the exact solution.

my question is if we deploy azure virtual machine using terraform and add the puppet client configuration in same VM code using shell scripting is it possible?? in azure terraform

**Comment by TomArcherMsft** [comment]
@THG-onkar 

We don't document/support Puppet so that's not something we could help with. 

If you've already searched the Terraform support channels (it sounds like you have, but I pasted the links below just in case), the only other suggestion would be to post a question on a peer-to-peer help site such as StackOverflow.com. 

I searched on StackOverflow and did find two posts where people asked about combining Terraform and Puppet on Azure.

** Stackoverflow
[StackOverflow questions "terraform+puppet+azure"][https://stackoverflow.com/search?q=%5Bterraform%5D+puppet+azure]

** Terraform support channels
- Questions, use-cases, and useful patterns: [Terraform section of the HashiCorp community portal](https://discuss.hashicorp.com/c/terraform-core)
- Provider-related questions: [Terraform Providers section of the HashiCorp community portal](https://discuss.hashicorp.com/c/terraform-providers)
