### ISSUE TITLE
Service Principal Creation Update

### ISSUE THREAD

**Issue by angelo-loria** [MicrosoftDocs/azure-dev-docs#152]
az ad sp create-for-rbac no longer takes --username --password, maybe update to az ad sp create-for-rbac --sdk-auth

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a310f63f-d11a-2b6a-0abd-4b75f543676b
* Version Independent ID: 21c8a211-1f42-9448-b72e-c84a52ae9ad2
* Content: [Tutorial - Scale Jenkins deployments with Azure VM agents](https://docs.microsoft.com/en-us/azure/developer/jenkins/scale-deployments-using-vm-agents#feedback)
* Content Source: [articles/jenkins/scale-deployments-using-vm-agents.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/jenkins/scale-deployments-using-vm-agents.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by Duffney** [comment]
Hey @angelo-loria,

I could not find any reference to the `az ad sp` command within the linked documentation. Perhaps it's been removed since you filed the issue, or the wrong article was linked. Because I can't find the reference, I'm closing the issue. Please let me know if the mistake remains and I'll investigate.

Thank you,
