### ISSUE TITLE
The public_key field is the SSH key, not the location in the vm

### ISSUE THREAD

**Issue by a30001539** [MicrosoftDocs/azure-dev-docs#183]
Probably should add something like (tf0.11 format)

`

    resource "tls_private_key" "example_ssh" {
      algorithm = "RSA"
      rsa_bits = 4096
    }

`

`
    output "tls_private_key" {
     value = "${tls_private_key.example_ssh.private_key_pem}" 
    }
`

and update the public_key field in the VM to be

`

    admin_ssh_key {
        username       = "azureuser"
        public_key     = "${tls_private_key.example_ssh.public_key_openssh}"
      }

`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3a8a34-f0f0-7aba-b45b-2c59d722b7de
* Version Independent ID: 667d19a1-ff34-3979-105c-c0a918d29707
* Content: [Quickstart - Create a Linux VM with infrastructure in Azure using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-linux-virtual-machine-with-infrastructure)
* Content Source: [articles/terraform/create-linux-virtual-machine-with-infrastructure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-linux-virtual-machine-with-infrastructure.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@a30001539 Thanks for the feedback. The code has been changed. The updated article should be published by Monday afternoon (PST).

**Comment by PylotLight** [comment]
Not sure if this is related, but "public_key = tls_private_key.example_ssh.public_key_openssh" currently results in error:
`Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="Destination path for SSH public keys is currently limited to its default value /home/azadmin/.ssh/authorized_keys  due to a known issue in Linux provisioning agent." Target="linuxConfiguration.ssh.publicKeys.path"`

Should I create a new issue for this somewhere?
