### ISSUE TITLE
cannot import name 'run' (aio_compat.py)

### ISSUE THREAD

**Issue by pauldj54** [MicrosoftDocs/azure-dev-docs#193]
[Enter feedback here]
I created a simple python function and deployed to a repo. A working colleague migrated to another repo. I cloned the code and tried to debug it again.

When I press F5  I got the following Error:

![image](https://user-images.githubusercontent.com/706754/84175896-e7388c00-aa80-11ea-8d54-2dfe0333252f.png)

I tried to recreate the function and spend several hours but I was not able to find a solution.

I started visual studio code from the conda shell activating the desired environment. I verified the environment is set in vs code. 

Any feedback would be appreciated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b9e736a-1c01-e6db-d567-650477725485
* Version Independent ID: d942390e-da29-c9ea-c8de-3b66db719a8e
* Content: [Step 4: Debug the Azure Functions Python code locally with VS Code](https://docs.microsoft.com/en-us/azure/developer/python/tutorial-vs-code-serverless-python-04?tabs=powershell)
* Content Source: [articles/python/tutorial-vs-code-serverless-python-04.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/tutorial-vs-code-serverless-python-04.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
The only thing that comes to mind is that the asyncio library in the conda environment is a different version that doesn't include the run function. I don't know enough about either to have the details, though.

In any case, because this is not an issue with the specific documentation in question (which is handled through this present repository), please file it instead with the repo for the Functions extension in VS Code, https://github.com/Microsoft/vscode-azurefunctions/issues. Thanks.
