### ISSUE TITLE
.ssh public private key left unfinished. so the ssh command will fail.

### ISSUE THREAD

**Issue by bruparel** [MicrosoftDocs/azure-dev-docs#242]
[Enter feedback here]

Really nice tutorial.  Public/Private key part is left unfinished.  As given, the ssh command to log into the created vm will fail.  Since the public and private keys are not stored in .ssh directory.  That should also be explained
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3a8a34-f0f0-7aba-b45b-2c59d722b7de
* Version Independent ID: 667d19a1-ff34-3979-105c-c0a918d29707
* Content: [Create a Linux VM with infrastructure in Azure using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-linux-virtual-machine-with-infrastructure)
* Content Source: [articles/terraform/create-linux-virtual-machine-with-infrastructure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-linux-virtual-machine-with-infrastructure.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by explodinghat** [comment]
Any update on this? I can create the resources using terraform from this guide, but then can't log on to the VM that's created. 

azureuser@[public IP]: Permission denied (publickey).

**Comment by TomArcherMsft** [comment]
Hi @explodinghat. I'll take a look next week and update this thread with my findings.

**Comment by TomArcherMsft** [comment]
Hi, @explodinghat

I was able to successfully create and SSH into the VM, but it took a little work as the article is out of date in some areas and not very explicit in the way in which you need to specify the SSH key.

## Issue 1 - Outdated provider block

The `provider` block should look as follows to eliminate warnings:

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "~>2.0"
    }
  }
}
provider "azurerm" {
  features {}
}
```

## Issue 2 - New "sensitive" annotation needed

The output of sensitive information - such as passwords - now requires the annotation that you realize that you're outputting such information. As this sample is meant for learning (instead of production), change the code that outputs the value of the "tls_private_key" value as follows:

```hcl
output "tls_private_key" { 
  value = tls_private_key.example_ssh.private_key_pem 
  sensitive = true
}
```

## Issue 3 - Using SSH to access the VM

The article needs to make more explicity what needs to be done here. What's missing is that once you have an SSH public key, you need to specify that key in some fashion. In the following example, I'm specifying the public key via the SSH public key file. You might need to change the location and file name based on where you create your SSH key.

```hcl
admin_ssh_key {
  username       = "azureuser"
  public_key     = file("~/.ssh/id_rsa.pub")
}
```

I'll update the article this week to correct these issues.

Please let me know if you have any questions.
Tom
