### ISSUE TITLE
Switching subscriptions not working

### ISSUE THREAD

**Issue by uday1kiran** [MicrosoftDocs/azure-dev-docs#280]
When I login with cli profile with python sdk and change the subscription the new subscription is not loading back.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 036cc96e-fbb8-bced-0a5b-ef6e332264b8
* Version Independent ID: 7b70016c-feb0-7da1-5995-2d1fa8bce9a9
* Content: [How to authenticate Python applications with Azure services](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=cmd)
* Content Source: [articles/python/azure-sdk-authenticate.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/azure-sdk-authenticate.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@uday1kiran Thanks for the issue.

Do the following steps describe what you're trying to do?

1. You have code that's using the CLI-based authentication method, https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=cmd#cli-based-authentication-development-purposes-only, which is using _subscription_client = get_client_from_cli_profile(SubscriptionClient)_.

2. You then change the CLI subscription with az account set (https://docs.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli?view=azure-cli-latest).

3. Running the code again does not use the new subscription as expected.

Let me know if I've understood correctly, then I can follow up with the appropriate people in the CLI and SDK teams.

**Comment by ukreddy-erwin** [comment]
@kraigb 
It is like I am having multiple subscriptions linked to my account.
So, I create a compute,subscription and lock client using the cli based authentication.
I have done some processing like lock/unlock with the resources in the current subscription.
After that, to manage other subscription resources.

```
lock_client = get_client_from_cli_profile(ManagementLockClient)
compute_client=get_client_from_cli_profile(ComputeManagementClient)
def switchSubscription(subscription_arg):
    # Get subs client
    subscription_client = get_client_from_cli_profile(SubscriptionClient)
    subscription = next(subscription_client.subscriptions.list())
    print(subscription.subscription_id)
    if subscription_arg != subscription_client:
        os.system("az account set --subscription "+subscription_arg)
        lock_client = get_client_from_cli_profile(ManagementLockClient)
        compute_client=get_client_from_cli_profile(ComputeManagementClient)
```
But still the clients are still using the old subscription.
I need to stop the script and run again to reflect the new subscription. Which is not ideal as I need to handle multiple subscriptions in a single run.

**Comment by kraigb** [comment]
Thanks--I'll check with the engineering teams and get back to you.

**Comment by kraigb** [comment]
Hi--some additional thoughts for you.

Invoking az account set via os.system doesn't accomplish what you seek. os.system runs the command in a subshell, not in the shell context in which the script was originally run. Therefore, the subscription change in that subshell is lost as soon as the command is complete.

In this case, you'll need to use either get_client_from_auth_file or get_client_from_json_dict so you can provide the JSON that specifies a subscription ID directly.

As an alternate, looking through the SDK source code (https://github.com/Azure/azure-sdk-for-python) the CLI profile appears to be loaded from the the file %AZURE_CONFIG_DIR%/azureProfile.json. So you could try to modify that file dynamically, but if you're doing that, it's just as easy, I think, to use get_client_from_json_dict.

You can also try changing the AZURE_SUBSCRIPTION_ID environment variable in the code using os.environ. I don't think this will work, but it's easy to try.

Otherwise, I direct you to file this issue on https://github.com/Azure/azure-sdk-for-python/issues to communicate with the engineering team. They might have additional ideas. But offhand, using get_client_from_auth_file and get_client_from_json_dict are what would give you the control over the subscription.

**Comment by ukreddy-erwin** [comment]
Hi @kraigb this file contains all the subscriptions(2 in my case),%AZURE_CONFIG_DIR%/azureProfile.json
But, one of them is set as default one and when I create a client object, it is using the default one. In our case, we need to pick from cli only but need to parse all subscriptions one by one. That's why we thought to change the default subscription at runtime but not use of it. For SubscriptionClient we can pass the relevant subscription as argument but not the compute_client or lock_client

**Comment by kraigb** [comment]
In that case, given that the CLI profile is going to default to the first subscription in that file, then you'll need to use get_client_from_auth_file or get_client_from_json_dict to specify the subscription directly for the various client objects.

**Comment by kraigb** [comment]
In the meantime, I'll add a note to the article about using the other authentication methods if you need to change subscriptions. If you want to make requests to enable other client objects to accept a subscription parameter, please file on  https://github.com/Azure/azure-sdk-for-python/issues.

**Comment by ukreddy-erwin** [comment]
Thank you @kraigb 
As the documentation not good, I wasn't able to get the method parameters.
But found this to create the client objects based on the subscription parameter.

```
kwargs = {}
        if subscription_arg:
            kwargs = {"subscription_id": "<subcription_id>"}
        lock_client = get_client_from_cli_profile(ManagementLockClient, **kwargs)
        compute_client=get_client_from_cli_profile(ComputeManagementClient, **kwargs)
        resource_client = get_client_from_cli_profile(ResourceManagementClient, **kwargs)
```
