### ISSUE TITLE
jenkins.service could not be found

### ISSUE THREAD

**Issue by chadmcrowell** [MicrosoftDocs/azure-dev-docs#331]
When I deployed this VM, it seems to be a vanilla Ubuntu box, no jenkins service is installed. Perhaps the marketplace image has been removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 115cdf49-6a35-aa52-de86-3cd8d0b2e3b9
* Version Independent ID: 40a3d5ca-157b-151f-a5e7-66fe71e41104
* Content: [Quickstart - Configure Jenkins using Azure CLI](https://docs.microsoft.com/en-us/azure/developer/jenkins/configure-on-linux-vm)
* Content Source: [articles/jenkins/configure-on-linux-vm.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/jenkins/configure-on-linux-vm.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@chadmcrowell Thanks for the feedback. I'm looking into the issue now.

**Comment by TomArcherMsft** [comment]
@chadmcrowell I just ran the steps without any issue. Are you you following the steps in this [article](https://review.docs.microsoft.com/en-us/azure/developer/jenkins/configure-on-linux-vm?branch=pr-en-us-1203)? I ask because you mention the Marketplace and the scripts run in the article's steps downloads Jenkins directly from the jenkins.io web site. I'm going to close the issue as the steps work in my testing. However, if you have more feedback, please let me know and I'll try to help.
