### ISSUE TITLE
Update azure-dev-docs as chef-client installation through Azure portal is no longer supported.

### ISSUE THREAD

**Issue by Vasu1105** [MicrosoftDocs/azure-dev-docs#333]
We have updated the azure-chef-extension docs for the same [here](https://docs.chef.io/azure_portal/)  but also need to update this https://docs.microsoft.com/en-us/azure/developer/chef/client-install-from-azure-portal.

**Comment by TomArcherMsft** [comment]
@Vasu1105 Thanks for your feedback. The Chef devhub is being retired from docs.microsoft.com. I'm currently updating the documentation to point to the Chef Software site.

**Comment by Vasu1105** [comment]
Thanks @TomArcherMsft could you please point me to the PR so that we able to track the progress ?

**Comment by TomArcherMsft** [comment]
@Vasu1105 The PR is in the internal (not public) repo. The changes will be live tomorrow morning.

**Comment by Vasu1105** [comment]
Okay @TomArcherMsft. Thanks for the update. Appreciate this !!

**Comment by TomArcherMsft** [comment]
@Vasu1105 The changes are live now. I'm not super happy with how it looks. I'd rather just have the index point to the Chef site instead of having what appears to be articles, but then each article has a blurb pointing to the Chef site. The challenge is that there are some limitations on my system's end that I need to work out as this isn't a normal situation. However, I wanted to get something online quickly so let customers know where the current documentation is, so that's a win.
