### ISSUE TITLE
Unable to run end-to-end test Teraform Test

### ISSUE THREAD

**Issue by sayom88** [MicrosoftDocs/azure-dev-docs#383]
I am following the following commands as per the tutorial, but still getting error. I am having Windows10 Laptop.

![image](https://user-images.githubusercontent.com/16284729/102757259-0ea8d380-4397-11eb-9e0a-cbcac3e1aa8c.png)

Also sharing the rsa file 
[id_rsa.txt](https://github.com/MicrosoftDocs/azure-dev-docs/files/5723274/id_rsa.txt)

**Comment by sayom88** [comment]
Hi @KarlErickson  @TomArcherMsft , any help on this please?Tnx.

**Comment by TomArcherMsft** [comment]
@sayom88 Apologies for the delay. I'm copying in one of the team that wrote that series of articles to help you.

@jcorioland Could you please assist?

**Comment by jcorioland** [comment]
Hello @sayom88 - if you are using PowerShell, instead of doing:

```Bash
export TEST_SSH_KEY_PATH="/home/USER/.ssh/id_rsa"
```

to configure the TEST_SSH_KEY_PATH environment variable, please try to use the following syntax:

```PowerShell
$Env:TEST_SSH_KEY_PATH = '/home/USER/.ssh/id_rsa'
```

You can read more about PowerShell and environment variables [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.1).

Hope this helps
Julien

cc @TomArcherMsft

**Comment by TomArcherMsft** [comment]
Thanks @jcorioland 

@sayom88, I'm closing the doc issue, but please let us know if you need further assistance.
