### ISSUE TITLE
Name of the main terraform configuration file

### ISSUE THREAD

**Issue by mahomedalid** [MicrosoftDocs/azure-dev-docs#401]
There is no mention of the name of the configuration file for the terraform, it was a little bit frustrating to need to jump to other places to find out. I suggest to include reference to https://learn.hashicorp.com/tutorials/terraform/azure-build?in=terraform/azure-get-started or just mention as a comment on the file that needs to be named `# main.tf`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68c31173-3e96-c871-5a2d-743a26522b4d
* Version Independent ID: 5b281d75-b37e-0301-e1fd-431e0344d0c7
* Content: [Quickstart - Configure Terraform using Azure PowerShell](https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-powershell)
* Content Source: [articles/terraform/get-started-powershell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/get-started-powershell.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@mahomedalid Thank you for your feedback. 

The configuration file can be any valid file name supported by your operating system. As this article is not a tutorial, we don't explicitly state what to name the configuration file. The article is meant to show the typical sequence of steps for creating the configuration file, and then creating and applying the execution plan.

The Terraform tutorials point to this article, so naming the file in this article would be confusing when customers click on this article from another article where the file has a different name.

**Having said that, we are planning to move away from this model because - as you noted - some customers find it frustrating to jump between articles.** 

Therefore, in the near future, the steps you're seeing in the quickstart will also be present in each tutorial (referencing the file name for the specific tutorial). 

Thanks again. Tom
