### ISSUE TITLE
Choose Docker File and give it a name?

### ISSUE THREAD

**Issue by ucheNkadiCode** [MicrosoftDocs/azure-dev-docs#42]
On number 2 of build a docker image, the docker build information is completely glossed over as to what to do. It's misleading because using docker build in the command pallete does not give other options to specify the tagging. It needs to be clarified with a sample example that the command should be in the terminal and is "docker build myregistryapphere.azurecr.io/myexpressapp:latest ." in order to create the same image we see in the example. 

On the push a docker image section, it is again not described how the use can push to their SPECIFIC registry. Just writing docker push will refer to docker.io which is a problem I ran into. It could be noted that they can just go to the image in the Images menu after it is properly built and  Right Click + Push. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1146a28d-d1ca-0660-fe00-b19e02aec28e
* Version Independent ID: 89eef017-0613-5d6f-7d9d-6b854b370339
* Content: [Create a container image for a Node.js app from Visual Studio Code](https://docs.microsoft.com/en-us/azure/javascript/tutorial-vscode-docker-node-03#feedback)
* Content Source: [javascript/tutorial-vscode-docker-node-03.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/javascript/tutorial-vscode-docker-node-03.md)
* Product: **azure-nodejs**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@ucheNkadiCode Thanks for alerting me that the flow had changed a bit; sometimes it's difficult to keep up with subtle changes.

In this case, the flow is as follows:

1. Create the Docker files as described in the article (answering "No" for Docker compose files, which isn't mentioned in the step).
2. Run Docker Images: Build Image as indicated.
3. After the build, right-click the image in the Docker explorer > Images section (expand the node for the image and right-click on "latest". This action prompts you to enter the full tags including the registry name.
4. A new node appears under Images with that fully tagged name. Expand that node and right-click "latest," then select Push. Because the image is tagged with the registry, VS Code will push to that registry.

I'll update the article with these changes (though you won't be able to see the PR because it'll be in our private internal repo). Note that I purposely don't give instructions to use docker commands directly, as the point of the tutorial is to keep readers in the flow of the VS Code UI whenever possible.

**Comment by kraigb** [comment]
Closing as the PR is merged.
