### ISSUE TITLE
Please correct the dockerfile ansible install method

### ISSUE THREAD

**Issue by drumforgod82** [MicrosoftDocs/azure-dev-docs#576]
The dockerfile will keep getting errors with the new version of ansible.  The correct install command for centos: 7 is the following:

yum install ansible; \

I just tested this out and the docker container is now working as it should.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51db2faf-908c-8022-fe37-693a800ce42a
* Version Independent ID: 41e60749-b1bb-ba0b-1b2a-100a3da5a277
* Content: [Quickstart - Configure Ansible in a Docker container](https://docs.microsoft.com/en-us/azure/developer/ansible/configure-in-docker-container?tabs=azure-cli%2Cbash)
* Content Source: [articles/ansible/configure-in-docker-container.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/configure-in-docker-container.md)
* Service: **ansible**
* GitHub Login: @Duffney
* Microsoft Alias: **jduffney**

**Comment by TomArcherMsft** [comment]
@drumforgod82 Thanks for the feedback. I'm reviewing/updating the article now....

**Comment by TomArcherMsft** [comment]
@drumforgod82 Would you mind sharing your Dockerfile to compare and test?

**Comment by drumforgod82** [comment]
FROM centos:7

RUN yum check-update; \
    yum install -y gcc libffi-devel python3 epel-release; \
    yum install -y python3-pip; \
    yum install -y wget; \
    yum clean all

RUN pip3 install --upgrade pip; \
    pip3 install --upgrade virtualenv; \
    pip3 install pywinrm[kerberos]; \
    pip3 install pywinrm; \
    pip3 install jmspath; \
    pip3 install requests; \
    yum install ansible -y; \
    wget -q https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt; \
    pip3 install -r requirements-azure.txt; \
    rm requirements-azure.txt; \
    ansible-galaxy collection install azure.azcollection


using pip3 install ansible does not work.  It needs to be yum install ansible.

James Dean
***@***.***

________________________________

**Comment by TomArcherMsft** [comment]
@drumforgod82 The installation of Ansible appears to work, but the running of the command to create a resource group failed (stating the import of the Python lib failed). I'm going to escalate this internally to a team that has Docker experience to try and resolve.

**Comment by TomArcherMsft** [comment]
@drumforgod82 Were you able to run the rest of the instructions - including creating the resource group - with your Dockerfile?

**Comment by drumforgod82** [comment]
No, I do not have a subscription or anything.  I just use the free stuff, lol.

James Dean
***@***.***

________________________________

**Comment by TomArcherMsft** [comment]
@drumforgod82 FYI, you can sign up for a free account using the link in the https://docs.microsoft.com/en-us/azure/developer/ansible/configure-in-docker-container?tabs=azure-cli%2Cbash#prerequisites.

**Comment by TomArcherMsft** [comment]
@drumforgod82 This issue has been fixed and the article update should be published tomorrow. Thanks again for your feedback.

**Comment by drumforgod82** [comment]
Awesome, thank you Tom!

James Dean
(636) 297-5499
***@***.***

On Sep 23, 2021, at 1:26 PM, Tom Archer ***@***.***> wrote:

﻿

@drumforgod82<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdrumforgod82&data=04%7C01%7C%7Ccb197c0154b14452824208d97ebfa05e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637680183897623460%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2B%2F0N1GcRIvNu8ysNYudtCwnuhFct2NvbLrOaiFjEMYM%3D&reserved=0> This issue has been fixed and the article update should be published tomorrow. Thanks again for your feedback.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fazure-dev-docs%2Fissues%2F576%23issuecomment-926052824&data=04%7C01%7C%7Ccb197c0154b14452824208d97ebfa05e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637680183897633451%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0NbN9w9w8Zfuh8Kmnvmt7MLXARJkk2T2u7DAy9TEMfw%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFRFHWZTIIEI67FQ66SMCALUDNWMLANCNFSM5CM5DRQA&data=04%7C01%7C%7Ccb197c0154b14452824208d97ebfa05e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637680183897633451%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MtxfoEywj%2Bs8UPzLkK4kTZFDPdegHK%2Fbz1NhIYTIdxY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ccb197c0154b14452824208d97ebfa05e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637680183897643445%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aTim7X4xvEBvNZoCf2JNVzp3894n3SPVz0BMYpX%2FbAQ%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ccb197c0154b14452824208d97ebfa05e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637680183897643445%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gncayWQQpx5tjjV1tgmET2WuCVgpI0fh5kQE1qX%2Fejc%3D&reserved=0>.

**Comment by Slowdive-Aideron** [comment]
@TomArcherMsft the Article is still faulty as far as i can tell. Problem is that installation of the azcollection requirements (python modules) is i believe done in a virtualenv, thus unavailable for the user running ansible.
No matter what you try and do the error is always something along these lines 


```bash
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.mgmt.monitor.version'
fatal: [localhost]: FAILED! => changed=false
  msg: Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on 74eb6265c86d's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter
```

**Comment by BenTheCloudGuy** [comment]
There appears to be issues with the dockerfile around installing azure.azcollection. 

154.7 WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
154.7 Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
154.7 To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
154.8 Requirement already satisfied: packaging in /usr/local/lib/python3.6/site-packages (from -r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 1)) (21.3)
154.8 Requirement already satisfied: requests[security] in /usr/local/lib/python3.6/site-packages (from -r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 2)) (2.27.1)
154.8 Requirement already satisfied: xmltodict in /usr/local/lib/python3.6/site-packages (from -r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 3)) (0.13.0)
155.0 Collecting msal==1.23.0
155.2   Downloading msal-1.23.0-py2.py3-none-any.whl (90 kB)
155.3 Collecting azure-cli-core==2.34.0
155.4   Downloading azure_cli_core-2.34.0-py3-none-any.whl (179 kB)
155.5 Collecting azure-common==1.1.11
155.6   Downloading azure_common-1.1.11-py2.py3-none-any.whl (9.7 kB)
155.7 Collecting azure-identity==1.7.0
155.7   Downloading azure_identity-1.7.0-py2.py3-none-any.whl (129 kB)
155.8 Collecting azure-mgmt-authorization==2.0.0
155.8   Downloading azure_mgmt_authorization-2.0.0-py2.py3-none-any.whl (465 kB)
155.9 Collecting azure-mgmt-apimanagement==3.0.0
156.0   Downloading azure_mgmt_apimanagement-3.0.0-py3-none-any.whl (588 kB)
156.2 Collecting azure-mgmt-batch==16.2.0
156.2   Downloading azure_mgmt_batch-16.2.0-py3-none-any.whl (126 kB)
156.3 Collecting azure-mgmt-cdn==11.0.0
156.4   Downloading azure_mgmt_cdn-11.0.0-py2.py3-none-any.whl (252 kB)
156.5 Collecting azure-mgmt-compute==26.1.0
156.6   Downloading azure_mgmt_compute-26.1.0-py3-none-any.whl (4.8 MB)
157.1 Collecting azure-mgmt-containerinstance==9.0.0
157.1   Downloading azure_mgmt_containerinstance-9.0.0-py2.py3-none-any.whl (57 kB)
157.2 Collecting azure-mgmt-core==1.3.0
157.2   Downloading azure_mgmt_core-1.3.0-py2.py3-none-any.whl (25 kB)
157.3 Collecting azure-mgmt-containerregistry==9.1.0
157.4   Downloading azure_mgmt_containerregistry-9.1.0-py3-none-any.whl (1.1 MB)
157.5 ERROR: Could not find a version that satisfies the requirement azure-containerregistry==1.1.0 (from versions: 1.0.0b1, 1.0.0b2, 1.0.0b3, 1.0.0b4, 1.0.0b5, 1.0.0b6, 1.0.0b7, 1.0.0, 1.1.0b1)
157.5 ERROR: No matching distribution found for azure-containerregistry==1.1.0
------
