### ISSUE TITLE
Helm 3.6.3 unknown command "init" for "helm"

### ISSUE THREAD

**Issue by Cristiano-Rosa** [MicrosoftDocs/azure-dev-docs#596]
Reference Page: https://docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-install-new#install-helm 

I get the following error when I try to run the below commands:

kubectl create serviceaccount --namespace kube-system tiller-sa
serviceaccount/tiller-sa created

kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller-sa
clusterrolebinding.rbac.authorization.k8s.io/tiller-cluster-rule created

helm init --tiller-namespace kube-system --service-account tiller-sa
Error: unknown command "init" for "helm"

Please confirm if this documentation is accurate for the latest available Helm version at the moment:
helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

Should I have another Helm version installed?

I found these:
https://stackoverflow.com/questions/59261340/helm-init-has-been-removed-in-version-3
https://helm.sh/blog/helm-v3-beta/

So it looks like helm init command has been removed.

If that is the case, can you please update our documentation accordingly?

Thanks,
Cristiano

**Comment by KarlErickson** [comment]
Hi @Cristiano-Rosa - thanks for the feedback! The documentation page you are referring to is in a different repository. Could you please reopen this issue using [this link](https://github.com/MicrosoftDocs/azure-docs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%2095812617-2cee-fb2c-2c6d-573f222033be%0A*%20Version%20Independent%20ID%3A%20bf51864f-646f-2fda-7842-b1f3cf2f9ce2%0A*%20Content%3A%20%5BCreating%20an%20ingress%20controller%20with%20a%20new%20Application%20Gateway%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fapplication-gateway%2Fingress-controller-install-new%23install-helm)%0A*%20Content%20Source%3A%20%5Barticles%2Fapplication-gateway%2Fingress-controller-install-new.md%5D(https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fazure-docs%2Fblob%2Fmaster%2Farticles%2Fapplication-gateway%2Fingress-controller-install-new.md)%0A*%20Service%3A%20**application-gateway**%0A*%20GitHub%20Login%3A%20%40Caya%0A*%20Microsoft%20Alias%3A%20**caya**) so that it will be in the azure-docs repository? Thanks!
