### ISSUE TITLE
JPA with Azure DB

### ISSUE THREAD

**Issue by prapakaransp** [MicrosoftDocs/azure-dev-docs#612]
[Enter feedback here]
I am trying JPA with the same config in springbot 2.5.4(latest) and getting the error below for creating table.

Config
spring.datasource.url=jdbc:sqlserver://XXXXXXX;databaseName=XXXXXX
spring.datasource.username=wmscatint
spring.datasource.password=XXXXXXX
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto = create-drop
logging.level.org.hibernate.SQL=DEBUG
************************************

Error:
Hibernate: drop table student
2021-09-28 15:47:55.190  WARN 9912 --- [  restartedMain] o.h.t.s.i.ExceptionHandlerLoggedImpl     : GenerationTarget encountered exception accepting command : Error executing DDL "drop table student" via JDBC Statement

org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "drop table student" via JDBC Statement
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]
GenerationTargetToDatabase.java:67
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.applySqlString(SchemaDropperImpl.java:375) ~[hibernate-core-5.4.32.Final.jar:5.4.32.Final]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97324ff3-4920-98ca-42e7-3eab1e77dc4f
* Version Independent ID: 771d24a6-683d-09a0-f1b8-598b2e3b3db4
* Content: [Use Spring Data JPA with Azure SQL Database](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jpa-with-azure-sql-server?toc=/azure/azure-sql/toc.json&bc=/azure/bread/toc.json)
* Content Source: [articles/java/spring-framework/configure-spring-data-jpa-with-azure-sql-server.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-data-jpa-with-azure-sql-server.md)
* Service: **sql-database**
* GitHub Login: @KarlErickson
* Microsoft Alias: **judubois**

**Comment by bbenz** [comment]
I couldn’t recreate the issue.  Successful screen shots below.  

I suspect it was one of two things, which I will be updating in the documentation:  
-The MS SQL password has to meet VERY specific criteria, and does not pass an obvious message if the setup fails due to a non-compliant password.  I’ll add a note and a link to [this documentation](https://docs.microsoft.com/en-us/sql/relational-databases/security/password-policy?view=sql-server-ver16) for the SQL Server QuickStart’s.
-If you use WSL on Windows, the WSL client ID is not the same as the Windows client ID, and the WSL client ID needs to be added to the database firewall.  I’ll update the QuickStarts with this detail as well.

![image](https://user-images.githubusercontent.com/2809036/179040189-827a78c9-21c3-4919-a764-4c9f286ab8a7.png)

![image](https://user-images.githubusercontent.com/2809036/179040321-301ae5ec-6b8e-4f3b-9619-14c9434e43d7.png)

**Comment by KarlErickson** [comment]
Closing as no-repro. Thanks for investigating (and for the upcoming doc updates), @bbenz!
