### ISSUE TITLE
Change in authentication sample code

### ISSUE THREAD

**Issue by shaheerem** [MicrosoftDocs/azure-dev-docs#709]
[Enter feedback here]
Kindly change armresources.NewResourceClient(subscriptionId, cred, nil) to armresources.NewClient(subscriptionId, cred, nil)
as the sdk repository doesn't have this former mentioned function anymore.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0512b7d6-3f16-303f-44dc-4e1595d5ca62
* Version Independent ID: 43cd9aca-e5ee-31f7-7c34-497c54ff9487
* Content: [Azure authentication with the Azure SDK for Go](https://docs.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication?tabs=bash)
* Content Source: [articles/go/azure-sdk-authentication.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/go/azure-sdk-authentication.md)
* Service: **azure**
* GitHub Login: @Duffney
* Microsoft Alias: **jduffney**

**Comment by Duffney** [comment]
Hi @shaheerem,

I appreciate you taking the time to file the issue, I'll get the docs updated per your suggestion.

Thank you, :)

**Comment by Duffney** [comment]
Hey @shaheerem.

I've made the suggested changes and updated the code to use the `NewClient` function instead of the `NewResourceClient` function. I also noticed that the readmes on pkg.dev also mention the old function. I'm working to update those references as well. A PR has been submitted will be merged shortly. You should see the docs update within the next 24-48 hours.

Thank you for taking the time to to submit the issue. :)

Have a wonderful day!

**Comment by Duffney** [comment]
#please-close
