### ISSUE TITLE
Unclear if Premium is truly a requirement for Spring Starter Azure Service Bus

### ISSUE THREAD

**Issue by pennstatephil** [MicrosoftDocs/azure-dev-docs#762]
Despite prerequisite section listing a "premium or higher" azure service bus requirement, the instructions seems to suggest that the example should function with standard or basic in the `pricing-tier` configuration variable. It would be great if the article was clarified to explain what will and won't work on each tier.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbecafd0-c6db-9cb0-c5a4-328946446ec6
* Version Independent ID: 40cea238-c2de-fd1d-fef7-c1a850b54158
* Content: [How to use the Spring Boot Starter for Azure Service Bus JMS](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **seal**

**Comment by yiliuTo** [comment]
Hi @pennstatephil , thanks for the advise and we will consider to improve the doc. Besides, as for the compatibilty of different tiers, you can refer to Service Bus MS docs for the supported JMS API specs on each tiers:
- https://docs.microsoft.com/azure/service-bus-messaging/jms-developer-guide?tabs=JMS-20
- https://docs.microsoft.com/azure/service-bus-messaging/jms-developer-guide?tabs=JMS-20

And for the library `spring-cloud-azure-starter-servicebus-jms`, it relys on spring-jms which uses JMS 2.0 specs, but since spring-jms by default supports  JMS 1.1 conventions, thus you can also use our starter with those 1.1 limited functionalities.

**Comment by KarlErickson** [comment]
Doc has been updated.
