### ISSUE TITLE
instruction not working on windows 11

### ISSUE THREAD

**Issue by malet-pr** [MicrosoftDocs/azure-dev-docs#783]
DAP server listening at: 127.0.0.1:65179
Build Error: go build -o d:\Documentos\PROGRAMACIÓN\GOLANG\codigo\sample-app\__debug_bin.exe -gcflags all=-N -l .
go: no such tool "compile"
go: no such tool "compile"
go: no such tool "compile"
go: no such tool "compile"
go: no such tool "compile"
go: no such tool "compile"
go: no such tool "compile"
go: no such tool "compile" (exit status 2)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb83b6cd-3526-b914-affa-73d510391b3a
* Version Independent ID: fb83b6cd-3526-b914-affa-73d510391b3a
* Content: [Configure Visual Studio Code for Go development](https://docs.microsoft.com/en-us/azure/developer/go/configure-visual-studio-code)
* Content Source: [articles/go/configure-visual-studio-code.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/go/configure-visual-studio-code.md)
* Service: **azure**
* GitHub Login: @Duffney
* Microsoft Alias: **jduffney**

**Comment by Duffney** [comment]
Hey @malet-pr,

I appreciate you submitting this issue, I'm looking into it and will try to repo the error you mentioned.

Thank you,

**Comment by Duffney** [comment]
I walked through the tutorial, but wasn't able to reproduce the error. Looking at the error message I'm fairly certain its due to not having all the Go Tools installed. Going through the steps listed under the [fifth heading](https://docs.microsoft.com/en-us/azure/developer/go/configure-visual-studio-code#4-update-the-go-tools) should get them all installed for you. Would you mind give that a try and let me know if it resolves the error?

Thank you,

**Comment by Duffney** [comment]
#please-close
