### ISSUE TITLE
Code snippet for SQLite connection string incorrect

### ISSUE THREAD

**Issue by wedgeley** [MicrosoftDocs/azure-dev-docs#830]
In the code snippet:

`var store = new OfflineSQLiteStore($"file://{dbPath}?mode=rwc");`

The "file://" should be "file:/".
The comment above the code snippet is correct.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd09c5f-3fe9-e58c-69d0-fa55157524f0
* Version Independent ID: 6d02e799-215b-6d05-8c43-edde20f68280
* Content: [How to use the .NET SDK for Azure Mobile Apps](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/howto/client/dotnet)
* Content Source: [articles/mobile-apps/azure-mobile-apps/howto/client/dotnet.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/azure-mobile-apps/howto/client/dotnet.md)
* Service: **mobile-services**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by adrianhall** [comment]
The SQLite connection string is indicated here: https://www.sqlite.org/c3ref/open.html#urifilenameexamples  As you can see from the list of examples, multiple mechanisms exist.  If dbPath is `/var/run/sqlite.db`, for example, the connection string would be `file:///var/run/sqlite.db` - this is similar to a direct example.  The reason we need the double slash is because of windows.  When you se the dbPath to `/c:/temp/sqlite.db`, you will get the proper URI `file:///c:/temp/sqlite.db`.  However, `file:/c:/temp/sqlite.db` does not work.

#please-close

**Comment by wedgeley** [comment]
Thanks for the quick and detailed response. I am using version 4.2.0 of the Microsoft.Azure.Mobile.Client packages and on my Windows box, the following works:
```
            string dbPath = Path.Combine(webHostEnvironment.WebRootPath, "init.db");
            var store = new OfflineSQLiteStore($"file:/{dbPath}");
```
Whereas the following does not:
```
            string dbPath = Path.Combine(webHostEnvironment.WebRootPath, "init.db");
            var store = new OfflineSQLiteStore($"file://{dbPath}");
```
The exception SqliteMessage is "invalid uri authority: ...". It is also happy with `file:///{dbPath}` and doesn't seem to mind whether "\" or "/" is the folder delimiter in dbPath.

**Comment by adrianhall** [comment]
You are using the v5.0.0 instructions with the v4.2.0 version of the library - that won't work.  Please update your library usage to use the latest package names (Microsoft.Datasync.Client) or use the v4.2.0 instructions (which doesn't use connection strings).

**Comment by wedgeley** [comment]
Yes, sorry, messed up that comment. 5.0.6 is the version number.
