### ISSUE TITLE
Python SDK docs don't cover control of logging within the SDK

### ISSUE THREAD

**Issue by jasonzio** [MicrosoftDocs/azure-dev-docs#84]
The Azure python SDK uses the python standard library package "logging" to emit logs. The SDK documentation doesn't cover how to control logging emitted by the SDK, the various logging levels used by the SDK, etc.

Sample questions which should be answered by the documentation:

- How can I silence all logging from the entire SDK
- How can I control logging for a single SDK module (azure.storage.blob or all of azure.storage)
- Within each module (e.g. azure.storage.blob), what logging is done at various levels (ERROR, WARNING, INFO, DEBUG)

There may actually be module-level defects that will arise from the development of the documentation I just described. For example, the azure.storage.blob module is incredibly noisy at the INFO level, but there doesn't appear to be any way to throttle just that module; the only way I could eliminate the blather at INFO for that module was:
```
azure_logger = logging.getLogger('azure')
azure_logger.setLevel(logging.WARNING)
```
Changes to the logger retrieved via getLogger('azure.storage') or getLogger('azure.storage.blob') was ineffective.

**Comment by kraigb** [comment]
@jasonzio Thanks for filing the issue and apologies for the belated acknowledgment. It's a great idea to doc all this, and I've got this on my backlog. I'll update here when there's progress though I'm not sure when, exactly, that will happen.

**Comment by jasonzio** [comment]
Do you need me to file issues against the SDK itself for the azure.storage logging issue I described here?

**Comment by kraigb** [comment]
Yes, for anything that's not specific docs-related, please file an issue in the SDK repo. Please @ me in those for awareness. Thanks.

**Comment by kraigb** [comment]
@jasonzio Wanted to let you know that at long last I'm finally getting to logging matters. I appreciate your patience. To answer one of your questions directly, have you tried this for storage?:

```
logger = logging.getLogger('azure.storage.blob')
logger.setLevel(logging.NOTSET)
```

Alternately, you could add a handler that directs the output for that module to a different place other than stdout or where you're picking up all other logs.

I'm otherwise still researching further details, though I can say that, in general, the logging instrumentation in the SDK is currently rather spotty; a few modules like storage, event hubs, and service bus do a fair amount of logging (event hubs especially), but most other modules do not. (And the management libraries don't use the logger at all.)

Much of the storage logging at DEBUG level, by the way, spits out the request/response details for its interactions with the REST API. From the looks of the SDK sources, it does this independently of the logging done in the central request/response parts of the SDK (in azure.core.pipeline.policies).

**Comment by jasonzio** [comment]
As I noted in my initial message, changes at the azure.storage.blob level were ineffective, but I admit I didn't try setLevel(logging.NOTSET); that never would have occurred to me. And even if it works, that would stop all logging from that module, and that's not actually my goal; I want to hear about errors, and even warnings. I just want the flood of logs at INFO.

You have given me another place to tinker, though; hadn't even occurred to me to look at azure.core.pipeline.policies as a centralized place to control logging.

I think the conversation so far makes my point about the need for a single document which describes (or points to module-level descriptions of) logging for the SDK. There's no obvious place to learn about how the SDK modules use each other, so there's no way to know where, within azure.core, one might apply logger.setLevel().

Spotty instrumentation or not, some guidance on how to control what _is_ there would be very useful. (And would also be a great jumping off point for filing bugs against individual modules due to their lack of logging instrumentation. :-) )

**Comment by kraigb** [comment]
Yep, that's why I'm working on such documentation. We've known the need for a while and it's finally bubbled up to the top of the SDK-docs piles for me.
