### ISSUE TITLE
Host restarts when virtual environment changes

### ISSUE THREAD

**Issue by stevenluda** [MicrosoftDocs/azure-dev-docs#89]
Was experimenting installing packages on the fly, i.e. adding the following line of code in the main() function to install pandas:
subprocess.check_call([".venv\\Scripts\\python", "-m", "pip", "install", "pandas"], shell=True)

Needed to do in this way instead of using requirements.txt due to lack of prior knowledge of required packages.

Debugging locally, the package is installed successfully, but the host process wants to restart right after it, and was unable to proceed with the debugging.

It seems any change to .venv on the side during the process would make the host want to restart.

Is there any work around to make host ignoring changes to .venv and proceeds?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32211a5a-ad60-b982-b27e-1f2c7caef1c9
* Version Independent ID: 32a098cf-c39d-342b-5b7e-d9a62f6a9454
* Content: [Step 4: Debug the Azure Functions Python code locally with VS Code](https://docs.microsoft.com/en-us/azure/python/tutorial-vs-code-serverless-python-04#feedback)
* Content Source: [python/tutorial-vs-code-serverless-python-04.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/python/tutorial-vs-code-serverless-python-04.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Hi @stevenluda--I don't know of any workaround for this particular question; if there was a simple means, it would be surfaced in the Python extension settings, but there aren't any applicable settings.

Because this matter pertains to the behavior of the Python extension in VS Code rather than being a docs issue, please create an issue on https://github.com/Microsoft/vscode-python/issues instead. That way you'll get in touch with the engineering team who can collect further details as necessary and perhaps provide a solution if there is one. In the meantime I'm closing this present docs issue. Thanks.
