### ISSUE TITLE
Getting 401unauthorized error on entering my creds

### ISSUE THREAD

**Issue by ShilpaCS18** [MicrosoftDocs/azure-dev-docs#893]
[Enter feedback here]
I tried the similar steps. We have a AD group linked to the application, added the permissions 
User.Read.All
User.ReadWrite.All and Directory.AccessAsUser.All.
but getting the message "needs permission to access resources in your organization that only an admin can grant. Please ask an admin to grant permission to this app before you can use it."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3233e2cc-1075-1c20-d8f8-65161949e341
* Version Independent ID: e3cef834-e81c-de56-9224-a22f7abdfb7e
* Content: [How to use the Spring Boot Starter for Azure Active Directory](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md)
* Service: **active-directory**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by KarlErickson** [comment]
@saragluna can you respond here? Thanks!

**Comment by saragluna** [comment]
@chenrujun please take a look at this issue.

**Comment by chenrujun** [comment]
Hi, @ShilpaCS18 

Thanks for reaching out.

> added the permissions
> User.Read.All
> User.ReadWrite.All and Directory.AccessAsUser.All.
> but getting the message "needs permission to access resources in your organization that only an admin can grant. Please ask an admin to grant permission to this app before you can use it."

It is expected behavior. 
1. **User.Read** does not require admin consent. 
2. But **User.Read.All**, **User.ReadWrite.All**, **Directory.AccessAsUser.All** require admin consent.

Refs:
1. https://docs.microsoft.com/en-us/graph/permissions-reference#user-permissions
![image](https://user-images.githubusercontent.com/13167207/189797414-8051b0ff-885f-4005-9b83-3a22c3ed239e.png)

2. https://docs.microsoft.com/en-us/graph/permissions-reference#directory-permissions
![image](https://user-images.githubusercontent.com/13167207/189797640-ed3d4002-f0fe-4f83-a888-1e3f0ad6f4fa.png)

3. https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent

**Comment by chenrujun** [comment]
Hi, @KarlErickson , please help to close this issue because there is no response for a long time.
