### ISSUE TITLE
Provide a script to register the app registration

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/azure-dev-docs#912]
Maybe helpful if you provide a PowerShell script to register the required app registration.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 711bca8f-ae02-ba38-c6cf-c8fac4357c57
* Version Independent ID: 711bca8f-ae02-ba38-c6cf-c8fac4357c57
* Content: [Add authentication to your Windows (WinUI3) app](https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/winui/authentication)
* Content Source: [articles/mobile-apps/azure-mobile-apps/quickstarts/winui/authentication.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/azure-mobile-apps/quickstarts/winui/authentication.md)
* Service: **mobile-services**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by adrianhall** [comment]
Thanks for the feedback.  Since this is a tutorial, we went with the simplest, most obvious way to do things.  I find that PowerShell and Azure CLI are non-obvious, and want to ensure that users know where to go in the portal to undo what they have done (or double check their work).

I'll consider adding a PowerShell or Azure CLI version in the future, but it won't happen for some time.  Since that's the case, we'll close this feedback for now.

#please-close
