### ISSUE TITLE
Add unit tests: handler

### ISSUE THREAD

**Issue by Lesrac** [MicrosoftDocs/azure-dev-docs#952]
Is there a way to test the "handler" logic itself within a UnitTest? Or is always an integration test required?
As there can be logic in the handler (like some validation) that I would like to verify in unit tests.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59f2ae26-8728-c449-ba2d-6f870080f07e
* Version Independent ID: 9d7345f9-d9be-1056-b293-18c16e524d3e
* Content: [Getting started with Spring Cloud Function in Azure](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/getting-started-with-spring-cloud-function-in-azure)
* Content Source: [articles/java/spring-framework/getting-started-with-spring-cloud-function-in-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/getting-started-with-spring-cloud-function-in-azure.md)
* Service: **azure-functions**
* GitHub Login: @KarlErickson
* Microsoft Alias: **judubois**

**Comment by KarlErickson** [comment]
@jdubois can you reply? Thanks!

**Comment by jdubois** [comment]
You can test the Spring Function part as described in https://docs.spring.io/spring-cloud-function/docs/current/reference/html/spring-cloud-function.html#_testing_functional_applications for example doing:

```
package com.example;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.http.RequestEntity;
import org.springframework.http.ResponseEntity;

import java.net.URI;

@SpringBootTest(classes = DemoApplication.class,
        webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public class HelloITTest {

    @Autowired
    private TestRestTemplate rest;

    @Test
    public void test() throws Exception {
        ResponseEntity<String> result = this.rest.exchange(
                RequestEntity.post(new URI("/")).body("yolo"), String.class);

        System.out.println(result.getBody());
        System.out.println(result.getStatusCode());
    }
}
```

BUT this has a limitation, you won't test the handler. It will test the Spring Function part, where the business logic should be, but not the handler, which is triggered by Azure Functions (so this is called from a non-Java process at some point). And if you want to change the HTTP Status code, that's the only place to change this.

You can test it by changing the HttpStatus code and doing something like:
```
curl -i -X POST http://localhost:7071/api/hello -d "{\"name\":\"Azure\"}"
```

You will see that it stays with a status code "200 OK" as the handler isn't called.

So that leaves you with 2 solutions: doing a mock or an integration test with something like Playwright/Selenium.

I believe that second option would be better, as it's interesting to test the whole function anyway: you never know, maybe a new version of Azure Functions will break something, so you should have a full integration test just in case. Also, using the consumption plan, you can even have the full function running in production at no cost, so I would take advantage of this.

**Comment by Lesrac** [comment]
Thanks for the reply @jdubois, so an integration test is needed.
That answers my question.
