### ISSUE TITLE
Need better code example of the datasyncclient authentication procedure for Identity Providers

### ISSUE THREAD

**Issue by norton287** [MicrosoftDocs/azure-dev-docs#967]
Going through this [Good Read](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/azure-mobile-apps/howto/client/dotnet.md) and the portion on the datasynclient authentication to an Azure App Service is lacking in a lot of information.  Could someone add the missing bits or give me a good social identity example for like Facebook or google?

**Comment by adrianhall** [comment]
We document how you wrap an access token into the overall library, using AAD as an example.  You can use the documentation from your identity provider to get the actual access token.  Because there are so many identity providers (and we can't document them all), we elected not to play favorites.

One of the things I think would be good to document is how to deal with WebAuthenticator, which is the preferred way in Xamarin and MAUI apps for dealing with social providers.  I'll add that to my list of things to do.

**Comment by norton287** [comment]
@adrianhall but in the how to with the sync client for app service authentication there is a big gap and leap of logic where you put todo in.  That's the key piece that could use a complete example of app service auth with the datasyncclient. Because it looks really great to use, but web authenticator to app service auth would be simpler.  I tried it first and keep getting a task cancelled exception when trying to login.

**Comment by norton287** [comment]
@adrianhall This is where I am stuck and cannot wrap my head around with the DatasyncClient method of authenticating to Azure App Service.

`
public AuthenticationProvider GetAuthenticationProvider()
    => new GenericAuthenticationProvider(GetTokenAsync);

// Or, if using Azure App Service Authentication and Authorization
// public AuthenticationProvider GetAuthenticationProvider()
//    => new GenericAuthenticationProvider(GetTokenAsync, "X-ZUMO-AUTH");

public async Task<AuthenticationToken> GetTokenAsync()
{
    // TODO: Any code necessary to get the right access token.
    
    return new AuthenticationToken 
    {
        DisplayName = "/* the display name of the user */",
        ExpiresOn = DateTimeOffset.Now.AddHours(1), /* when does the token expire? */
        Token = "/* the access token */",
        UserId = "/* the user id of the connected user */"
    };
}
`
I'm stuck where the TODO part is, I'm not following with what to put there.  I'm not making the leap to understand.  Can you provide an example please?

**Comment by adrianhall** [comment]
There is a full example for Azure AD in the Quickstart tutorials.  It walks through exactly what code to put there for that specific identity provider and includes full instructions on how to set up Azure AD properly for that use case.  For example, here is the MAUI version which covers iOS, Android, and Windows: https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication

**Comment by norton287** [comment]
So you are saying it doesn't have a native implementation to authenticate to app service configured with social identities directly other than using another login provider?

Then get cracking on Web Authenticator, Sir! LOL!

**Comment by adrianhall** [comment]
Correct - when we switched to ASP.NET Core, we made the decision to support JWT based authorizations, but not to be opinionated about which providers to support.  As a result, all providers are now supported - you just have to set it up so that you get the appropriate access token.

I will work on WebAuthenticator documentation.

**Comment by norton287** [comment]
@adrianhall I have the following code and it is opening the chrome tab and taking me to the social identity provider but I'm not getting redirected back to the app.  WebAuthenticator is hanging and the App Service just drops me at /.auth/login/done.

Here is what I have:

`
private static DatasyncClient client;
private AuthenticationToken token;

public static AuthenticationProvider GetAuthenticationProvider() => new GenericAuthenticationProvider(GetTokenAsync, "X-ZUMO-AUTH");

//Main Body

private void DoLogin()
{
AuthenticationProvider authProvider = GetAuthenticationProvider();
        Client = new DatasyncClient("https://myappserviceapp.azurewebsites.net", authProvider);

await authProvider.LoginAsync().ConfigureAwait(false);
}

public static async Task<AuthenticationToken> GetTokenAsync()
    {
        Debug.WriteLine("It was Called!");

       var authEndpoint = new Uri(Client.Endpoint, "/.auth/login/google");

        var callback = new Uri("myappserviceapp://easyauth.callback");

        try
        {
            var authResult = await WebAuthenticator.AuthenticateAsync(authEndpoint, callback);

            return new AuthenticationToken
            {
                ExpiresOn = (DateTimeOffset)authResult.ExpiresIn,
                Token = authResult.AccessToken
            };

            Console.WriteLine(authResult.ExpiresIn);
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            throw;
        }
    }

`

I have the WebAuthenticator callback setup done in the Android project as well.  And the WebAuthenticator setup in manifest done as well.

I'm not sure what is wrong, any pointers?

**Comment by adrianhall** [comment]
See [MAUI Issue #11641](https://github.com/dotnet/maui/issues/11641) and the associated PR I have open to fix the problem in MAUI Essentials (PR dotnet/maui#11710)

**Comment by norton287** [comment]
@adrianhall Thank you Sir!

**Comment by adrianhall** [comment]
So - short version here.  There is a way to do this, but it's "complicated".  

Basically, WebAuthenticator open a web browser to a known address, then waits for a response on the callback URL that is "well-formed", which means having a fragment in the callback URL #acces_token={something}&expires={secs since epoch} - Azure App Service Authentication uses a different format, so you have to convert.

To do this, create an ASP.NET Core controller on GET /mobileauth - this will receive the access token from App Service, and allow you to decode the fragment provided and convert to the form required by WebAuthenticator - generally myapp://auth/#access_token={something}&expires={secs since epoch} - then the WebAuthenticator captures this

You then call WebAuthenticator the same way, but make sure Azure App Service Authentication redirects to your /mobileauth controller (which will then redirect back to WebAuthenticator with the decoded result).  Xamarin.Forms showed how to do this with this controller: https://github.com/xamarin/Essentials/blob/develop/Samples/Sample.Server.WebAuthenticator/Controllers/MobileAuthController.cs and MAUI works the same way.

I've put in a fix to MAUI Essentials WebAuthenticator to provide a response decoder.  The basics are that WebAuthenticator doesn't need the middle man controller because we can decode anything.  However, that won't make it in for some time (probably one of the next couple of MAUI releases).  As a result, I'm going to write a short blog post on how to do this without.

**Comment by norton287** [comment]
Link the blog post here to please @adrianhall.  So I need to setup an ASP. NET CORE server to be an intermediary like in the Authenticator directions with just on controller?

John

**Comment by adrianhall** [comment]
I'd add the controller to your existing Azure Mobile Apps service - it's just an ASP.NET core service at the end of the day, so you can add whatever you need to.

**Comment by norton287** [comment]
@adrianhall Actually it's one level of difficulty higher, its a function app, I'm using App Service Authentication with it.

**Comment by adrianhall** [comment]
Now I am confused.  Azure Mobile Apps and the datasyncclient do not work with a Function App.

I think you are now in "unsupported" land for Azure Mobile Apps.  You need to go get assistance from the Azure Functions folks.

**Comment by norton287** [comment]
@adrianhall it still uses app service authentication and has all the end end points likev/.auth/me and uses easyauth.callback like any app service authentication mobile app uses.  I used mobile service authentication with it for a long time.

**Comment by adrianhall** [comment]
The latest DatasyncClient does not implement authentication - it provides a mechanism for you to submit an authentication token with your requests.  How you get that authentication token is up to you.    Once you have the token, we provide mechanisms for submitting that token via an Authorization bearer header or via an alternative header.

Your problem is actually nothing to do with Azure Mobile Apps, since we don't prescribe how to get a token.  It's the fact that you cannot get a token from App Service Authentication / Authorization.  

You can certainly continue using the old library (we're not going to take it down - we're just not supporting it any more).

**Comment by norton287** [comment]
@adrianhall correct.  mobile service authentication doesn't work with MAUI though on Android.  it wants to load a bunch of old packages.

I will wait until the decoder is in authenticator and that should work great.

**Comment by adrianhall** [comment]
Ack.  I'd also go over to the Functions or App Service docs and ask for instructions on how to authenticate with MAUI as a feature request.

**Comment by adrianhall** [comment]
#please-close
