### ISSUE TITLE
Python Azure SDK authentication docs incorrect?

### ISSUE THREAD

**Issue by nickmhankins** [MicrosoftDocs/azure-dev-docs#97]
Hi,

In the example from [here](https://docs.microsoft.com/en-us/azure/python/python-sdk-azure-authenticate?view=azure-python#mgmt-auth-token):

```python
from azure.mgmt.compute import ComputeManagementClient
from azure.common.credentials import ServicePrincipalCredentials

# Retrieve credentials from secure storage. Never hard-code credentials into code.

credentials = ServicePrincipalCredentials(tenant = <tenant_id>,
    client_id = <client_id>, secret = <secret>)

client = ComputeManagementClient(credentials, <subscription_id>)
```

It looks like `ServicePrincipalCredentials` should be a class in `azure.common.credentials`, but the [documentation doesn't reflect that](https://docs.microsoft.com/en-us/python/api/azure-common/azure.common.credentials?view=azure-python).

I can see the `ServicePrincipalCredentials` class in `msrestazure`, as [documented here  ](https://docs.microsoft.com/en-us/python/api/msrestazure/msrestazure.azure_active_directory.serviceprincipalcredentials?view=azure-python).  Was this class recently moved?

Thanks

**Comment by kraigb** [comment]
@nickmhankins Yes, there were some changes and the docs are a little out of date. I'm working on an update but no definite ETA yet.

**Comment by kraigb** [comment]
@nickmhankins Apologies for my slow response--I've been working through the details amidst other priorities. :) 

The code in the article is actually correct, and in some ways so is the documentation. That is, you do use _from azure.common.credentials import ServicePrincipalCredentials_ for the ServicePrincipalCredentials class, which is why the code is correct. That said, the object itself does ultimately come from the msrestazure module, so the reference docs https://docs.microsoft.com/en-us/python/api/msrestazure/msrestazure.azure_active_directory.serviceprincipalcredentials?view=azure-python, are also correct in their own way.

But I agree it's confusing, because the ServicePrincipalCredentials class (and its peers) should be documented under azure.common.credentials. I'll file that issue separately with the SDK docs repo, and will reference this issue, which I'll now close. Thanks for pointing this out.

Ref doc issue: https://github.com/MicrosoftDocs/azure-docs-sdk-python/issues/632
