### ISSUE TITLE
Python app deployment hangs at "Creating zip package"

### ISSUE THREAD

**Issue by josh-qf** [MicrosoftDocs/azure-dev-docs#98]
https://docs.microsoft.com/en-us/azure/python/tutorial-deploy-app-service-on-linux-05
Python app deployment stuck at "Creating zip package".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 911c2447-654c-3c24-d17c-86e1c902d32d
* Version Independent ID: 543854d9-d319-70d7-ecb8-60c4bda3ccd7
* Content: [Step 5: Deploy a Python web app to Azure App Service on Linux using VS Code](https://docs.microsoft.com/en-us/azure/python/tutorial-deploy-app-service-on-linux-05)
* Content Source: [python/tutorial-deploy-app-service-on-linux-05.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/python/tutorial-deploy-app-service-on-linux-05.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@josh-qf Thanks for the report; I'll try to replicate the issue in the next few days.

**Comment by kraigb** [comment]
@josh-qf Hi--I tested the process again with a simple Flask app and the deployment worked fine. Because this is potentially an engineering issue or something specific to your code, I suggest you file an issue https://github.com/Azure/azure-sdk-for-python/issues so the engineering team can work with you on the specifics.

In the meantime, I'm closing this issue because it's not specifically about the docs. Thanks.
